# Generated by Django 5.2.7 on 2025-10-17 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefono", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Vivienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("direccion_completa", models.TextField()),
                ("referencia_catastral", models.CharField(max_length=20, unique=True)),
                (
                    "nombre_aseguradora_impagos",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "contrato_modelo",
                    models.FileField(blank=True, null=True, upload_to="contratos/"),
                ),
                (
                    "factura_luz",
                    models.FileField(blank=True, null=True, upload_to="facturas/luz/"),
                ),
                (
                    "factura_agua",
                    models.FileField(blank=True, null=True, upload_to="facturas/agua/"),
                ),
                (
                    "factura_gas",
                    models.FileField(blank=True, null=True, upload_to="facturas/gas/"),
                ),
                ("link_anuncio", models.URLField(blank=True, max_length=500)),
                (
                    "precio_mensualidad",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("duracion_visita_minutos", models.PositiveIntegerField(default=30)),
                (
                    "administradores",
                    models.ManyToManyField(to="propiedades.administrador"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HorarioVisita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "vivienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="propiedades.vivienda",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("vivienda", "dia_semana", "hora_inicio", "hora_fin")
                },
            },
        ),
    ]
