# Generated by Django 5.2.7 on 2025-10-17 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                (
                    "sueldo_mensual",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sueldo mensual bruto en euros",
                        max_digits=10,
                    ),
                ),
                ("numero_inquilinos", models.PositiveIntegerField(default=1)),
                ("numero_menores", models.PositiveIntegerField(default=0)),
                (
                    "mascota",
                    models.BooleanField(default=False, help_text="¿Tiene mascotas?"),
                ),
                (
                    "puesto_trabajo",
                    models.TextField(
                        help_text="Describa los puestos de trabajo de los inquilinos adultos"
                    ),
                ),
                (
                    "fumador",
                    models.BooleanField(default=False, help_text="¿Es fumador?"),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_hora", models.DateTimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                            ("REALIZADA", "Realizada"),
                        ],
                        default="CONFIRMADA",
                        max_length=20,
                    ),
                ),
                (
                    "cancelacion_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("veces_cancelada", models.PositiveIntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "vivienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitas",
                        to="propiedades.vivienda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "ordering": ["fecha_hora"],
                "unique_together": {("vivienda", "fecha_hora")},
            },
        ),
    ]
