# Generated by Django 5.2.7 on 2025-10-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0002_visita"),
    ]

    operations = [
        migrations.AddField(
            model_name="visita",
            name="motivo_cancelacion",
            field=models.CharField(
                blank=True,
                help_text="Motivo por el que se canceló la visita.",
                max_length=255,
                null=True,
            ),
        ),
    ]
