# Generated by Django 5.2.7 on 2025-10-17 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0003_visita_motivo_cancelacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudDeDocumentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de envío de documentos"),
                            ("COMPLETADA", "Documentación recibida"),
                            ("EN_REVISION", "En revisión"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "token_acceso",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "visita",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitud_de_documentacion",
                        to="propiedades.visita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de documentación",
                "verbose_name_plural": "Solicitudes de documentación",
            },
        ),
        migrations.CreateModel(
            name="InquilinoDocumentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("dni_nif_nie", models.CharField(max_length=20)),
                (
                    "dni_anverso",
                    models.FileField(upload_to="documentacion/dni_anverso/"),
                ),
                (
                    "dni_reverso",
                    models.FileField(upload_to="documentacion/dni_reverso/"),
                ),
                (
                    "contrato_trabajo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentacion/contrato_trabajo/",
                    ),
                ),
                (
                    "ultima_nomina",
                    models.FileField(
                        blank=True, null=True, upload_to="documentacion/nominas/"
                    ),
                ),
                (
                    "penultima_nomina",
                    models.FileField(
                        blank=True, null=True, upload_to="documentacion/nominas/"
                    ),
                ),
                (
                    "antepenultima_nomina",
                    models.FileField(
                        blank=True, null=True, upload_to="documentacion/nominas/"
                    ),
                ),
                (
                    "renta_anual",
                    models.FileField(
                        blank=True,
                        help_text="Para autónomos",
                        null=True,
                        upload_to="documentacion/renta/",
                    ),
                ),
                ("iban", models.CharField(max_length=34)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquilino_documentacion",
                        to="propiedades.solicituddedocumentacion",
                    ),
                ),
            ],
        ),
    ]
