# Generated by Django 5.2.7 on 2025-10-17 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0003_visita_motivo_cancelacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudSeguro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de envío de documentos"),
                            ("COMPLETADA", "Documentación recibida"),
                            ("APROBADA", "Aprobada por aseguradora"),
                            ("RECHAZADA", "Rechazada por aseguradora"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "token_acceso",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "visita",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitud_seguro",
                        to="propiedades.visita",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoInquilino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=255)),
                ("dni_nif_nie", models.CharField(max_length=20)),
                ("dni_anverso", models.FileField(upload_to="seguro/dni_anverso/")),
                ("dni_reverso", models.FileField(upload_to="seguro/dni_reverso/")),
                (
                    "contrato_trabajo",
                    models.FileField(
                        blank=True, null=True, upload_to="seguro/contrato_trabajo/"
                    ),
                ),
                (
                    "ultima_nomina",
                    models.FileField(
                        blank=True, null=True, upload_to="seguro/nominas/"
                    ),
                ),
                (
                    "penultima_nomina",
                    models.FileField(
                        blank=True, null=True, upload_to="seguro/nominas/"
                    ),
                ),
                (
                    "antepenultima_nomina",
                    models.FileField(
                        blank=True, null=True, upload_to="seguro/nominas/"
                    ),
                ),
                (
                    "renta_anual",
                    models.FileField(
                        blank=True,
                        help_text="Para autónomos",
                        null=True,
                        upload_to="seguro/renta/",
                    ),
                ),
                ("iban", models.CharField(max_length=34)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_inquilinos",
                        to="propiedades.solicitudseguro",
                    ),
                ),
            ],
        ),
    ]
